FROM imos/icfpc2020:bootstrap

################################################################################
# Environment variables (required for installation)
# NOTE: environment variables not required for installation can be placed in
# `Configurations` section.
################################################################################

ENV PATH=/work/bin:/usr/local/cargo/bin:/usr/local/go/bin:$PATH
ENV GOROOT=/usr/local/go
ENV GOPATH=/go
ENV RUSTUP_HOME=/usr/local/rustup
ENV CARGO_HOME=/usr/local/cargo
