name: Rust

on:
  push:
    branches: [ submission ]
  pull_request:
    branches: [ submission ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --offline
    - name: Run tests
      run: cargo test --verbose
