name: Rust

on:
  push:
    branches: [ submission ]
  pull_request:
    branches: [ submission ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd app && cargo build --release --offline
    - name: Run tests
      run: cd app && cargo test --verbose
