version: '3'

services:
  mysql:
    image: imos/icfpc2020:sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${UNAGI_PASSWORD}
    links:
      - mysql
    ports:
      - 4040:80
