#!/usr/bin/env bash

if [ "${UNAGI_INIT:-}" != '' ]; then
  export XUNAGI_INIT=yes
  mkdir -p /mnt/nfs
  sshfs guest@104.198.82.168:/home/guest/nfs /mnt/nfs \
      -o reconnect,uid=0,gid=0,delay_connect
  export XUNAGI_SSHFS=yes
  commit_id="local"
  head_commit_id="remote"
  if [ -d ~/.cache/icfpc2020/github ]; then
    export XUNAGI_SYNC=yes
    curl --silent \
        https://storage.googleapis.com/icfpc2020-asia/info/GIT_COMMIT_ID \
        >/tmp/GIT_HEAD_COMMIT_ID &
    git_commit_id_pid="$!"
    rsync -a --delete ~/.cache/icfpc2020/github/ /repo/
    rsync -a --delete ~/.cache/icfpc2020/github/ /repo/
    wait "${git_commit_id_pid}"
    commit_id="$(cd /repo; git rev-parse HEAD)"
    head_commit_id="$(cat /tmp/GIT_HEAD_COMMIT_ID)"
  else
    export XUNAGI_SYNC=no
  fi

  if [ "${commit_id}" != "${head_commit_id}" ]; then
    export XUNAGI_PULL=yes
    pushd /repo >/dev/null
    git pull -q -f
    git reset -q --hard
    git clean -qdf
    rsync -a --delete /repo/ ~/.cache/icfpc2020/github/
    popd >/dev/null
  else
    export XUNAGI_PULL=no
  fi
else
  export XUNAGI_INIT=no
fi

exec "$@"
